### ISSUE TITLE
Checklist of algorithms to implement

### ISSUE THREAD

**Issue by jtquach1** [jtquach1/cs498#1]
# Lexical Analysis (Chapter 2)
- [x] Convert a regular expression to an NFA
- [x] Compute ε-closure for a set of states and for a single state in an NFA
- [x] Convert an NFA to a DFA
- [x] 5/24 - Minimize (ie, prune) a DFA
*Finished Chapter 2 on 6/7/21*

# Parsing (Chapter 3)
- [x] 6/7 - *Finished on 6/8/21* Compute first and follow sets of symbols in a CFG
- [x] 6/7 - *Finished on 6/9/21* Build the LL(1) parse table for a CFG
- [x] 6/14 - *Finished on 6/10/21* Implement LL(1) parsing
- [x] 6/21 - Remove left recursion in a CFG
- [x] 6/28 - *Finished on 6/23/21* Compute the closure of an itemset
- [x] 7/5 - *Finished on 6/24/21* Compute the transition from an itemset on a grammar symbol
- [x] 7/12 - *Finished on 6/29/21* Build the LR(1) canonical collection of itemsets
- [x] 7/19 - *Finished on 7/15/21* Build the LR(1) parse (Action and Goto) tables
- [x] 7/26 - *Finished on 7/16/21* Implement LR(1) parsing

~~# Register Allocation (Chapter 7)~~
~~- [ ] 8/2 - Compute local and global liveness sets~~
~~- [ ] 8/9 - Build liveness intervals~~
~~- [ ] 8/16 - Perform register allocation using graph coloring~~
